config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: { registrations: 'users/registrations' } 
  root 'homes#top'
  
  resources :users, only: [:show] do
    member do
      get :likes
    end
  end

  resources :comics, only: [:index] do
    resources :scenes , except: [:show] do
      resources :likes, only: [:create, :destroy]
    end
    collection do
      get :select
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  mount_uploader :image, ImageUploader
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true
  
  has_many :scenes
  has_many :likes
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  protected

  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  def after_update_path_for(resource)
    user_path(current_user)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user

  def show
    @scenes = Scene.where(user_id: @user.id).includes(:user, :comic).page(params[:page]).per(5)
  end

  def likes
    @likes = Like.where(user_id: @user.id).includes(:scene).page(params[:page]).per(5)
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/views/users/_user_menu.html.haml
.container--user__left
  - if @user.image.present?
    = image_tag @user.image.url,size:"200x200",class: "person--icon"
  - else
    = image_tag "person.png",size:"200x200",class: "person--icon"
  %h3
    = @user.username
  .container--user__left__menu
    = link_to "編集", edit_user_registration_path
    = link_to "ログアウト", destroy_user_session_path, method: :delete
    = link_to "名場面を投稿する", select_comics_path
    - if request.path_info == user_path(current_user)
      = link_to "いいねした名場面一覧", likes_user_path(current_user)
    - else
      = link_to "投稿した名場面一覧", user_path(current_user)
    

app/views/users/likes.html.haml
.main--wrapper
  .container--user.clearfix
    %h2 プロフィール
    .user--contents
      = render partial: "user_menu"
      .container--user__right
        %h3 いいねした名場面
        .container--user__right__list
          %ul
            - @likes.each do |like|
              %li
                .user--scene--image
                  - scene = Scene.find_by(id: like.scene_id)
                  = image_tag scene.image.url,size:"200x250"
                .user--scene--contents
                  %h3
                    = scene.title
                  %p.scene--comic--title
                    (
                    = scene.comic.title
                    )
                  .iine--content
                    = link_to "/comics/#{scene.comic_id}/scenes/#{scene.id}/likes/#{like.id}" , method: :delete do
                      %i.iine--button いいねを解除する
                  %p.scene--comic--content
                    = scene.content
    .pagination--block
      = paginate @likes

app/views/users/show.html.haml
.main--wrapper
  .container--user.clearfix
    %h2 プロフィール
    .user--contents
      = render partial: "user_menu"
      .container--user__right
        %h3 このユーザーが投稿した名場面
        .container--user__right__list
          %ul
            - @scenes.each do |scene|
              %li
                .user--scene--image
                  = image_tag scene.image.url,size:"200x250"
                .user--scene--contents
                  %h3
                    = scene.title
                  %p.scene--comic--title
                    (
                    = scene.comic.title
                    )
                  .edit--button
                    = link_to "編集","/comics/#{scene.comic_id}/scenes/#{scene.id}/edit"
                  %p.scene--comic--content
                    = scene.content
    .pagination--block
      = paginate @scenes