config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: { registrations: 'users/registrations' } 
  root 'homes#top'
  
  resources :users, only: [:show] do
    member do
      get :likes
    end
  end

  resources :comics, only: [:index] do
    resources :scenes , except: [:show] do
      resources :likes, only: [:create, :destroy]
    end
    collection do
      get :select
    end
  end
end

app/models/comic.rb
class Comic < ApplicationRecord
  has_many :scenes

  validates :title, presence: true, uniqueness: true
  validates :image, presence: true

  mount_uploader :image, ImageUploader
end

app/controllers/comics_controller.rb
class ComicsController < ApplicationController
  before_action :set_comics

  def index
  end

  def select
  end

  def set_comics
    @comics = Comic.all
  end
end

app/views/comics/index.html.haml
.main--wrapper
  .container--comics
    %h2 漫画一覧
    %p.sentence 画像をクリックすると名場面一覧が表示されます。
    .container--comics__list.clearfix
      - @comics.each do |comic|
        = link_to comic_scenes_path(comic) do
          .comic--content
            = image_tag comic.image_url,size:"200x250"
            %h3
              = comic.title
            

app/views/comics/select.html.haml
.main--wrapper
  .container--comics
    %h2 名場面投稿
    %p.sentence 好きな漫画をクリックしてお気に入りの名場面を投稿しよう
    .container--comics__list.clearfix
      - @comics.each do |comic|
        = link_to new_comic_scene_path(comic) do
          .comic--content
            = image_tag comic.image_url,size:"200x250"
            %h3
              = comic.title