config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: { registrations: 'users/registrations' } 
  root 'homes#top'
  
  resources :users, only: [:show] do
    member do
      get :likes
    end
  end

  resources :comics, only: [:index] do
    resources :scenes , except: [:show] do
      resources :likes, only: [:create, :destroy]
    end
    collection do
      get :select
    end
  end
end

app/views/layouts/_footer.html.haml
.footer
  %span
    Copyright © 2019

app/views/layouts/_header.html.haml
.header
  .header__logo
    = link_to root_path do
      = image_tag "logo.png" , class: "logo--image" 
  .header__menus
    %ul
      - if user_signed_in?
        %li 
          = link_to comics_path do
            COMICS
        %li 
          = link_to select_comics_path do
            NEW POST
        %li 
          = link_to user_path(current_user) do
            PROFILE
      - else
        %li 
          = link_to new_user_registration_path do
            SIGNUP
        %li
          = link_to new_user_session_path do
            .login--btn
              LOGIN

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ComicApl
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render partial: "layouts/header"
    = yield
    = render partial: "layouts/footer"